version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/lentil1016/descheduler
    steps:
      - checkout
      - run: go get -v github.com/lentil1016/descheduler
